import Head from 'next/head'
import { Inter } from '@next/font/google'
import Navbar from '../components/Navbar/index'
import Slider from '../components/Slider'
import SwiperData from "../json/swiperimagesdata.json"
import MainCategoriesData from "../json/MainCategoriesData.json"
import MainCategories from '../components/MainCategories'
import Products from '../json/Products.json'
import ProductCard from '../components/ProductCard'
import styles from '../styles/Home.module.css'
import { useState  , useEffect} from 'react'
import Footer from '../components/Footer'
import LandingShippingOptions from '../components/LandingShippingOptions'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {


  const swiperData = Object.assign(SwiperData.swiper)
  const MainCategorie = Object.assign(MainCategoriesData.categories)
  const bestProducts = Object.assign(Products.products)

  const [addToCart , setAddToCart] = useState([])
  const [addToWish , setAddToWish] = useState([])


  return (
    <>
      <Head>
        <title>My Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <body className={styles.container}>
          <Navbar/>
          <Slider data={swiperData}/>
          <MainCategories data={MainCategorie}/>
          {/*Best products section */}
          <div className={styles.bestSellingContainer}>
            <h2>Best Selling Product</h2>
            <div className={styles.cardsContainer}>
              {
                bestProducts.map((element : any , index : number) => {
                  return(
                  (index < 12)&&<ProductCard key={element.id} addedToCart = {addToCart} setAddedToCart = {setAddToCart} addToWish = {addToWish} setAddToWish = {setAddToWish} id = {element.id} name = {element.name} imageUrl = {element.imageUrl}  price = {element.price} reductionPercentage = {element.reductionPercentage}  addedToWishList = {element.addedToWishList}  rating = {element.rating}/>
                  )
                })
              }
            </div>
          </div>
          <div style={{marginBottom : '300px' , zIndex : '100'}}>
            <LandingShippingOptions/>
          </div>
        </body>
        <Footer/>
      </main>
    </>
  )
}
