import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Navbar from '../components/Navbar/index'
import styles from '../styles/Home.module.css'
import Slider from '../components/Slider'
import SwiperData from "../json/swiperimagesdata.json"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const swiperData = Object.assign(SwiperData.swiper)

  return (
    <>
      <Head>
        <title>My Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <body style={{margin : '0px' ,padding : '0px'}}>
          <Navbar/>
          <Slider data={swiperData}/>
        </body>
      </main>
    </>
  )
}
